### ISSUE TITLE
Is this based on CodeMirror 1 or 2?

### ISSUE THREAD

**Issue by rayrfan** [Dominator008/CodeMirror-minified#13]

**Comment by Dominator008** [comment]
This is based on CodeMirror 5.

**Comment by rayrfan** [comment]
Oops, thank you!

**Comment by rayrfan** [comment]
This may be another silly question but is it possible to pack CodeMirror into a single .js file instead of the mess it is now?

**Comment by Dominator008** [comment]
https://github.com/Dominator008/CodeMirror-minified/blob/master/lib/codemirror.js
I believe this is what you meant by a single `.js` file.

**Comment by rayrfan** [comment]
Currently I'm using [Editor.md](https://github.com/pandao/editor.md) which is based on CodeMirror and as a result I have to include so many folders and files into my project.  So I was wondering if it is possible to combine CodeMirror's addons, modes, themes etc. together with its core library into a bundle of one or a couple of files instead of many folders and files?

**Comment by Dominator008** [comment]
It might be possible to do so by adding the files you need to CodeMirror’s Rollup config:
https://github.com/codemirror/CodeMirror/blob/master/rollup.config.js
I haven’t tried it myself though.

**Comment by rayrfan** [comment]
Thank you for pointing that out, I posted this [question in their forum](https://discuss.codemirror.net/t/does-codemirror-have-a-single-bundle-of-all-the-files/2115) and got this answer.

> CodeMirror doesn’t come with anything like this, and its rollup.config.js is just used to build the core library (lib/codemirror.js). Bundler software like webpack can create such files for you, though. (Or, if you don’t want to use a module system, just concatenating the files should work too.)

**Comment by rayrfan** [comment]
Hi Michael, how hard do you think bundling CodeMirror into a single file or just a few files would be and is that something your project would consider? Thanks!

**Comment by Dominator008** [comment]
https://raw.githubusercontent.com/Dominator008/CodeMirror-minified/f4a96bd282b46664a3f0d302d05c1cec82c6ad6c/lib/codemirror-bundled.js

Could you check if this file works? I simply concatenated all the minified JS files.

**Comment by rayrfan** [comment]
I created this [demo repo](https://github.com/FanrayMedia/codemirror-bundled-demo) for you to see what's happening, I got this error

> Uncaught ReferenceError: test is not defined
    at codemirror-bundled.js:584
