### ISSUE TITLE
Link codemirror.net in readme points to version 6

### ISSUE THREAD

**Issue by pmario** [Dominator008/CodeMirror-minified#24]
The link to codemirror.net in the readme should now point to: https://codemirror.net/5/

**Comment by pmario** [comment]
Same thing at: https://github.com/Dominator008/CodeMirror-minified/blob/8e177c875a27d4b356679d8409bf815cc435d8c5/package.json#L36

**Comment by Dominator008** [comment]
Fixed. Thanks.
